package: yform_export
version: '0.0.1-dev'
author: eaCe
supportpage: https://github.com/eaCe/yform_export

requires:
    packages:
        yform: '^4.0.0'
    redaxo: '^5.10.0'
    php:
        version: '>=7.4'
