package: yform_export
version: '0.0.1'
author: eaCe
supportpage: https://github.com/eaCe/yform_export

requires:
    packages:
        yform: '^4.0.0'
    redaxo: '^5.10.0'
    php:
        version: '>=7.4'
installer_ignore:
    - node_modules
    - .git
    - .gitignore
    - .github
    - tests
    - .tools
    - package.json
    - yarn.lock
    - resources
    - .editorconfig
    - .eslintrc.js
    - .stylelintrc.js
    - phpcs.xml
    - phpunit.xml.dist
    - composer.json
    - composer
    - lib/composer.json
    - lib/composer.lock
